accounts:
  - name: validator-a
    coins: ["1000000stake", "1000000000samoleans"]
  - name: alice
    coins: ["1000000stake", "100000000000samoleans"]
    address: "chaina1v2hn2yg8hxwcsqp5w2ghan6ufvztaz5tg0qd89"
validator:
  name: validator-a
  staked: "1000000stake"
build:
  binary: chain-a
client:
  vuex:
    path: "vue/src/store"
genesis:
  chain_id: "chain-a"
init:
  home: "./.chain-a"
host:
  rpc: "0.0.0.0:26657"
  api: "0.0.0.0:1317"
  grpc: "0.0.0.0:9090"
  dev-ui: "0.0.0.0:12345"
  p2p: "0.0.0.0:26659"
  prof: "0.0.0.0:6060"
  frontend: "0.0.0.0:8080"
